### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by neheller** [MathOnco/HAL#2]
The GitHub Icon at the top-right of the [documentation](http://halloworld.org/start_here.html) points at https://github.com/torococo/HAL which doesn't seem to exist.

**Comment by neheller** [comment]
The "Download" button has this issue as well.

**Comment by JeffreyWest** [comment]
Thanks for pointing this out @neheller! I've removed all references to https://github.com/torococo/HAL and replaced with the correct link: https://github.com/MathOnco/HAL

**Comment by rschenck** [comment]
Closing this issue. Please reopen if you discover that there's another missing :)
