### ISSUE TITLE
Can diffusion-decay, advection-diffusion, and advection-diffusion-decay PDEs be modeled?

### ISSUE THREAD

**Issue by JulianoGianlupi** [MathOnco/HAL#4]
Hello!

Sorry if this is not the most appropriate venue to ask.

Can HAL solve diffusion-decay, advection-diffusion, and advection-diffusion-decay equations? Looking at the source code I can see pure diffusion and pure advection, but nothing with decay or combining diffusion and advection, i.e.,

- $\frac{\partial C}{\partial t} = D\nabla^2C - \gamma C$
- $\frac{\partial C}{\partial t} = \nabla (D\nabla C - v c) - \gamma C$

Thanks!

**Comment by torococo** [comment]
Hello, yes it can solve diffusion and advection, as well as decay. The correct usage of the PDE Grid in HAL is to call all of the diffusion, advection, reaction functions you want to apply for a given time-step then call the Update function to advance the state of the PDE to the next time-step.

**Comment by JulianoGianlupi** [comment]
Perfect, thanks! Are there any examples I could look at in the repo?

**Comment by torococo** [comment]
Sure, there's a demo in the Examples folder that shows how the different
PDE functions can be combined. It's called _4PDEexample.java

**Comment by JulianoGianlupi** [comment]
Thanks!
